# Salatuk — Upload Keystore Generation
#
# IMPORTANT: The keystore generated by this script is REQUIRED to publish updates
# to the Play Store. If you lose it OR forget the password, you can NEVER publish
# an update to the same app listing again — you'd have to release under a new
# package ID and lose all existing users.
#
# Back this file up in at least 2 secure locations (password manager + offline drive).
# Do NOT commit it to git.

param(
    [Parameter(Mandatory=$true)][string]$KeystorePassword,
    [Parameter(Mandatory=$true)][string]$KeyPassword,
    [string]$Alias = "salatuk-upload",
    [string]$DName = "CN=Salatuk, OU=Mobile, O=Salatuk, L=Beirut, ST=Beirut, C=LB",
    [string]$OutDir = "$PSScriptRoot\..\android\app"
)

$ErrorActionPreference = "Stop"

if (-not $env:JAVA_HOME) {
    $env:JAVA_HOME = "C:\Program Files\Microsoft\jdk-17.0.19.10-hotspot"
}
$keytool = Join-Path $env:JAVA_HOME "bin\keytool.exe"
if (-not (Test-Path $keytool)) { throw "keytool not found at $keytool" }

if (-not (Test-Path $OutDir)) { New-Item -ItemType Directory -Path $OutDir -Force | Out-Null }
$keystorePath = Join-Path $OutDir "upload-keystore.jks"

if (Test-Path $keystorePath) {
    throw "Keystore already exists at $keystorePath — refusing to overwrite. Move or delete it first if you really want to regenerate (this will lock you out of updating the existing Play Store listing)."
}

& $keytool -genkey -v `
    -keystore $keystorePath `
    -alias $Alias `
    -keyalg RSA `
    -keysize 2048 `
    -validity 10000 `
    -storepass $KeystorePassword `
    -keypass $KeyPassword `
    -dname $DName

if ($LASTEXITCODE -ne 0) { throw "keytool failed with exit $LASTEXITCODE" }

# Write the key.properties file Gradle reads. This file is gitignored.
$keyProps = Join-Path $PSScriptRoot "..\android\key.properties"
@"
storePassword=$KeystorePassword
keyPassword=$KeyPassword
keyAlias=$Alias
storeFile=upload-keystore.jks
"@ | Set-Content -Path $keyProps -Encoding utf8

Write-Output ""
Write-Output "=== Keystore generated ==="
Write-Output "  Keystore: $keystorePath"
Write-Output "  Props:    $keyProps"
Write-Output ""
Write-Output "BACK UP THE KEYSTORE FILE AND THE PASSWORDS NOW."
Write-Output "Without them, you can never update this app on the Play Store again."
